M48
; DRILL file {KiCad (6.0.11)} date Wed Jan  3 02:28:45 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-03T02:28:45+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.400
%
G90
G05
T1
X203.458Y-65.365
T2
X180.232Y-51.357
X196.192Y-51.357
T0
M30
